-- Eliminar la base de dato dbCurso
DROP DATABASE dbPizzaJava;

-- Crear base de datos dbPizzaJava
CREATE DATABASE IF NOT EXISTS dbPizzaJava
DEFAULT CHARACTER SET utf8;

-- Poner en uso la base de datos
USE dbPizzaJava;

-- Crear la tabla UBIGEO
CREATE TABLE UBIGEO 
(
    CODUBI CHAR(6),
    DEPAUBI VARCHAR(50) NOT NULL,
    PROVUBI VARCHAR(50) NOT NULL,
    DISTUBI VARCHAR(50) NOT NULL,
    CONSTRAINT CODUBI_PK PRIMARY KEY(CODUBI)
);

-- Crear la tabla CLIENTE
CREATE TABLE CLIENTE 
(
    CODCLI CHAR(4),
    NOMCLI VARCHAR(20) NOT NULL,
    APECLI VARCHAR(20) NOT NULL,
    FECNACICLI date NOT NULL,
    TELFCLI CHAR(9),
    DIRRECCLI VARCHAR(80),
    DNICLI CHAR(8) NOT NULL,
    SEXCLI CHAR(1) NOT NULL,
    CODUBI CHAR(6),
    CONSTRAINT CODCLI_PK PRIMARY KEY(CODCLI)
);

-- Crear la tabla VENDEDOR
CREATE TABLE VENDEDOR 
(
    CODVEN CHAR(4),
    NOMVEN VARCHAR(20) NOT NULL,
    APEVEN VARCHAR(20) NOT NULL,
    SEXVEN CHAR(1) NOT NULL,
    TELFVEN CHAR(9),
    DIRRECVEN VARCHAR(80),
    DNIVEN CHAR(8) NOT NULL,
    CONSTRAINT CODVEN_PK PRIMARY KEY(CODVEN)
);

-- Crear la tabla BOLETA
CREATE TABLE BOLETA
(
	CODBOL CHAR(4),
    FECBOL DATE NOT NULL,
    CODCLI CHAR(4),
    CODVEN CHAR(4),
    CONSTRAINT CODBOL_PK PRIMARY KEY(CODBOL)
);

-- Crear la tabla PIZZA
CREATE TABLE PIZZA
(
	CODPIZ CHAR(4),
    TIPPIZ VARCHAR(50) NOT NULL,
    TAMPIZ CHAR(10) NOT NULL,
    PRECPIZ DECIMAL(10,2) NOT NULL,
    CONSTRAINT CODPIZ_PK PRIMARY KEY(CODPIZ)
);

-- Crear la tabla BOLETA_DETALLE
CREATE TABLE BOLETA_DETALLE
(
	CODBOLDET CHAR(4),
    CANTPROD INT NOT NULL,
    CODBOL CHAR(4),
    CODPIZ CHAR(4),
    CONSTRAINT CODBOLDET_PK PRIMARY KEY(CODBOLDET)
);

-- Relacionar la tabla UBIGEO con CLIENTE
ALTER TABLE CLIENTE
ADD CONSTRAINT UBIGEO_CLIENTE_CODUBI
FOREIGN KEY (CODUBI) REFERENCES UBIGEO (CODUBI);

-- Relacionar la tabla CLIENTE con BOLETA
ALTER TABLE BOLETA
ADD CONSTRAINT CLIENTE_BOLETA_CODCLI
FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI);

-- Relacionar la tabla VENDEDOR con BOLETA
ALTER TABLE BOLETA
ADD CONSTRAINT VENDEDOR_BOLETA_CODVEN
FOREIGN KEY (CODVEN) REFERENCES VENDEDOR (CODVEN);

-- Relacionar la tabla BOLETA con BOLETA_DETALLE
ALTER TABLE BOLETA_DETALLE
ADD CONSTRAINT BOLETA_BOLETA_DETALLE_CODBOL
FOREIGN KEY (CODBOL) REFERENCES BOLETA (CODBOL);

-- Relacionar la tabla PIZZA con BOLETA_DETALLE
ALTER TABLE BOLETA_DETALLE
ADD CONSTRAINT PIZZA_BOLETA_DETALLE_CODPIZ
FOREIGN KEY (CODPIZ) REFERENCES PIZZA (CODPIZ);